### ISSUE TITLE
After adding a student, the website defaults to two columns. 

### ISSUE THREAD

**Issue by souvorinkg** [DiscoTrayStudios/CommencementSeating#10]
After adding a student, the website defaults to two columns. Refreshing the page reverts back to the original design. After adding a student, the website defaults to two columns. Refreshing the page reverts back to the original design. 
<img width="780" alt="image" src="https://github.com/DiscoTrayStudios/CommencementSeating/assets/89923856/fc25385a-72d1-4671-b5c2-9689ffc06abb">

**Comment by mgoadric** [comment]
Yes. This looks like after the add, the page goes to https://localhost:7133/Students instead of https://localhost:7133/Students?chartNum=1
